name: Build
run-name: Build
on:
    workflow_dispatch:
        inputs:
            profile:
                description: 'Build Profile'
                default: 'test'
                required: true
                type: choice
                options:
                - dev
                - staging
                - production
            version_code:
                description: 'Version Code'
                required: true
                type: string
            branch:
                description: 'Branch'
                required: true
                type: string

jobs:
    build:
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v3
              with:
                repository: hoangminh1789/auto_build
                ref: ${{ inputs.branch }}
                clean: false
                fetch-depth: 0
            - name: build
              run: echo Hello world